### ISSUE TITLE
SearchSong.js randomize function too long

### ISSUE THREAD

**Issue by th1rst** [acapasso90/kkslider#1]
Aloha!

Saw your post on /r/reactJS and since the main issue was already resolved, I thought I'd point out another issue:

Your "randomize" function can be MASSIVELY shortened by using:

>   const getRandomSong = () => {
>       const randomNumber = **Math.floor(Math.random() * 95)**;
>       const ApiURL = `https://acnhapi.com/v1a/songs/${randomNumber}`;
>       axios.get(ApiURL).then(playSong);
>   };

What this does is:
Math.random -> generate random number between 0 and 1
Math.random() * 95 -> generate a random number between 0 and 95 (or set whatever number fits here)
Math.floor -> removes the decimal points after the number. So instead of 58.345345345 you get 58

So you'll save ~100 Lines of code.

Also, you should use a Linter like ESLint.

Happy coding ✌️

**Comment by acapasso90** [comment]
Thank you so much!! I knew there had to be a better way to do it, I really appreciate the help! I'll look into a linter for sure.
